### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by deepak2431** [airplanedev/lib#485]
I am running a SQL task to display table records. But on running the task it shows the resource not found but I can see the resources under Resource in the studio. 

![image](https://user-images.githubusercontent.com/44617923/208842689-c7a2f382-d927-483f-b17f-deccfaeb9cb5.png)
![image](https://user-images.githubusercontent.com/44617923/208842738-e1e529ce-2ea4-4002-b219-ab8bd668b294.png)

**Comment by deepak2431** [comment]
Okay, it also worked when I added the resources in the Local environment. So, the resources added under the prod env aren't automatically loaded for local?

**Comment by zhan-airplane** [comment]
Hi @deepak2431, yes, as you have said, we don't automatically fall back to an environment in the studio.

If you want to use resources from a prod environment automatically you have to pass that in explicitly (e.g. `airplane dev --env=prod`). The top of the studio page should have a `Fallback Environment` that indicates which remote environment (if any) tasks or resources are being pulled from.

We'll see if we can do a better job around documenting this behavior, thanks for this report!
